import { makeStyles, tokens } from '@fluentui/react-components'

import { mobileTouchTarget, NARROW_VIEWPORT_QUERY } from '@/styles/touchTargets'

export const useConversationTreeStyles = makeStyles({
  root: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
    padding: tokens.spacingVerticalM,
    backgroundColor: tokens.colorNeutralBackground1,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  title: {
    fontSize: tokens.fontSizeBase500,
    fontWeight: tokens.fontWeightSemibold,
  },
  spacer: { flex: 1 },
  workspaceSelect: {
    width: '16rem',
    minWidth: 0,
    maxWidth: '100%',
    '& select': { minWidth: 0, textOverflow: 'ellipsis' },
  },
  body: {
    display: 'flex',
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    [NARROW_VIEWPORT_QUERY]: { flexDirection: 'column', overflowY: 'auto' },
  },
  outline: {
    width: '12rem',
    flexShrink: 0,
    overflowY: 'auto',
    padding: tokens.spacingVerticalS,
    borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
    [NARROW_VIEWPORT_QUERY]: { width: 'auto', maxHeight: '10rem' },
  },
  stack: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalM,
    minWidth: 0,
  },
  row: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
  },
  outlineButton: {
    ...mobileTouchTarget,
    justifyContent: 'flex-start',
    textAlign: 'left',
    width: '100%',
    overflowWrap: 'anywhere',
  },
  canvas: {
    flex: 1,
    minWidth: 0,
    minHeight: '22rem',
    backgroundColor: tokens.colorNeutralBackground2,
    '& .react-flow__controls-button': { ...mobileTouchTarget },
    '& .react-flow__attribution': {
      backgroundColor: tokens.colorNeutralBackground1,
      '& a': { color: tokens.colorNeutralForeground2 },
    },
  },
  inspector: {
    width: '25rem',
    maxWidth: '100%',
    flexShrink: 0,
    overflowY: 'auto',
    padding: tokens.spacingVerticalL,
    backgroundColor: tokens.colorNeutralBackground1,
    borderLeft: `1px solid ${tokens.colorNeutralStroke2}`,
    [NARROW_VIEWPORT_QUERY]: { width: 'auto', overflowY: 'visible' },
  },
  muted: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    overflowWrap: 'anywhere',
  },
  empty: {
    margin: 'auto',
    maxWidth: '42rem',
    padding: tokens.spacingVerticalXXXL,
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalL,
  },
  card: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    overflow: 'hidden',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusLarge,
    padding: tokens.spacingVerticalM,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    boxShadow: tokens.shadow4,
    '&[data-state="draft"]': { border: `1px dashed ${tokens.colorNeutralStroke1}`, color: tokens.colorNeutralForeground3 },
    '&[data-selected="true"]': {
      outline: `2px solid ${tokens.colorBrandStroke1}`,
      boxShadow: tokens.shadow8,
    },
    '&[data-kept="true"]': { borderLeft: `4px solid ${tokens.colorBrandStroke1}` },
    '&[data-pruned="true"]': {
      opacity: 0.6,
      border: `1px dashed ${tokens.colorNeutralStrokeAccessible}`,
      backgroundColor: tokens.colorNeutralBackground3,
    },
  },
  preview: {
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    overflowWrap: 'anywhere',
    whiteSpace: 'pre-wrap',
    fontSize: tokens.fontSizeBase200,
    marginTop: tokens.spacingVerticalS,
  },
  responsePreview: {
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    paddingTop: tokens.spacingVerticalS,
  },
  expandedPrompt: {
    fontSize: tokens.fontSizeBase300,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    maxHeight: '30%',
    overflowY: 'auto',
    paddingTop: tokens.spacingVerticalS,
  },
  expandedResponse: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    fontSize: tokens.fontSizeBase300,
  },
  groupHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalM,
    padding: tokens.spacingVerticalS,
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  button: { ...mobileTouchTarget },
  pipelinePreview: {
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    minHeight: tokens.lineHeightBase100,
  },
  stackedCard: {
    boxShadow: `4px 4px 0 ${tokens.colorNeutralBackground3}, 8px 8px 0 ${tokens.colorNeutralStroke2}`,
    animationName: { from: { opacity: 0.4, transform: 'translateY(4px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
    animationDuration: '180ms',
    '@media (prefers-reduced-motion: reduce)': { animationDuration: '0ms' },
  },
  scoreIndicator: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXXS, marginTop: tokens.spacingVerticalXS },
  scoreTrack: {
    position: 'relative',
    height: '6px',
    marginLeft: tokens.spacingHorizontalXS,
    marginRight: tokens.spacingHorizontalXS,
    backgroundImage: `linear-gradient(to right, ${tokens.colorPaletteGreenBackground3}, ${tokens.colorPaletteYellowBackground3}, ${tokens.colorPaletteRedBackground3})`,
    borderRadius: tokens.borderRadiusCircular,
  },
  scoreMarker: {
    position: 'absolute',
    width: '3px',
    height: '10px',
    top: '-2px',
    transform: 'translateX(-50%)',
    backgroundColor: tokens.colorNeutralForeground1,
  },
  branchCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    padding: tokens.spacingVerticalM,
  },
  pipelineStep: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalXS,
    padding: tokens.spacingVerticalS,
    backgroundColor: tokens.colorNeutralBackground2,
    borderRadius: tokens.borderRadiusMedium,
  },
  parameters: {
    margin: 0,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    fontSize: tokens.fontSizeBase200,
    fontFamily: tokens.fontFamilyMonospace,
  },
  disclosure: {
    '& summary': {
      ...mobileTouchTarget,
      cursor: 'pointer',
      paddingTop: tokens.spacingVerticalS,
      paddingBottom: tokens.spacingVerticalS,
      color: tokens.colorBrandForeground1,
    },
  },
  dialog: { maxWidth: '44rem', width: '90vw' },
  planEditor: {
    minHeight: '18rem',
    fontFamily: tokens.fontFamilyMonospace,
  },
  transcript: {
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '32rem',
    overflowY: 'auto',
  },
})
