import { makeStyles, tokens } from '@fluentui/react-components'

import { mobileTouchTarget, mobileTouchTargetHeight, NARROW_VIEWPORT_QUERY } from '@/styles/touchTargets'

export const useTreeAssistantPanelStyles = makeStyles({
  root: {
    display: 'flex',
    flexDirection: 'column',
    flex: '0 1 22rem',
    width: 'min(22rem, 100%)',
    maxWidth: '100%',
    minWidth: 0,
    minHeight: 0,
    boxSizing: 'border-box',
    overflow: 'hidden',
    backgroundColor: tokens.colorNeutralBackground1,
    borderLeft: `1px solid ${tokens.colorNeutralStroke2}`,
    '&[hidden]': { display: 'none' },
    [NARROW_VIEWPORT_QUERY]: {
      flex: '1 1 auto',
      width: '100%',
      height: '100%',
      borderLeftWidth: 0,
    },
  },
  header: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
    padding: tokens.spacingHorizontalM,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  title: {
    margin: 0,
    fontSize: tokens.fontSizeBase400,
    fontWeight: tokens.fontWeightSemibold,
  },
  content: {
    flex: '1 1 auto',
    minHeight: 0,
    overflowY: 'auto',
    overflowWrap: 'anywhere',
    padding: tokens.spacingHorizontalM,
  },
  stack: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalM,
  },
  transcript: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalL,
    listStyleType: 'none',
    margin: 0,
    padding: 0,
  },
  message: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalXS,
    minWidth: 0,
  },
  changes: {
    margin: 0,
    paddingLeft: tokens.spacingHorizontalL,
    '& li': { paddingBottom: tokens.spacingVerticalS, overflowWrap: 'anywhere' },
  },
  change: {
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    paddingTop: tokens.spacingVerticalS,
  },
  fields: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: tokens.spacingVerticalXS,
    margin: 0,
    '& dt': { color: tokens.colorNeutralForeground2, fontSize: tokens.fontSizeBase200 },
    '& dd': { margin: 0, marginBottom: tokens.spacingVerticalS, overflowWrap: 'anywhere' },
  },
  identifiers: {
    overflowWrap: 'anywhere',
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
  },
  resolved: {
    padding: tokens.spacingHorizontalS,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    color: tokens.colorNeutralForeground2,
  },
  userText: {
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
  },
  proposal: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    minWidth: 0,
    maxWidth: '100%',
    maxHeight: 'min(32rem, 65dvh)',
    boxSizing: 'border-box',
    overflow: 'hidden',
    padding: tokens.spacingHorizontalM,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  proposalBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    minHeight: 0,
    overflowY: 'auto',
    overflowWrap: 'anywhere',
    '& > *': { flexShrink: 0 },
  },
  muted: {
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
  },
  actions: {
    display: 'flex',
    flexShrink: 0,
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
  },
  button: { ...mobileTouchTarget },
  disclosure: {
    cursor: 'pointer',
    ...mobileTouchTargetHeight,
  },
  json: {
    margin: 0,
    maxHeight: '16rem',
    overflow: 'auto',
    paddingTop: tokens.spacingVerticalS,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
  },
  composer: {
    display: 'flex',
    flexShrink: 0,
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    padding: tokens.spacingHorizontalM,
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  composerActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
  },
  autoSwitch: { ...mobileTouchTargetHeight },
  input: { ...mobileTouchTargetHeight },
})
